//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterBuddy.Data.BarterBuddyEDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BarterBuddyContext : DbContext
    {
        public BarterBuddyContext()
            : base("name=BarterBuddyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BBUser> BBUsers { get; set; }
        public virtual DbSet<BBUserDetail> BBUserDetails { get; set; }
    }
}
