//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterBuddy.Data.BarterBuddyEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBUserDetail
    {
        public long UserDetailID { get; set; }
        public long UserID { get; set; }
        public string WhatsAppNumber { get; set; }
        public string Name { get; set; }
    
        public virtual BBUserDetail BBUserDetails1 { get; set; }
        public virtual BBUserDetail BBUserDetail1 { get; set; }
    }
}
