//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterBuddy.Data.BarterBuddyEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBUser
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int LoginType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifidDate { get; set; }
    }
}
